default:
  just --list

run-dev:
    uv run uvicorn src.main:app --port 5000 --reload

run:
    uv run uvicorn src.main:app --port 5000


create-db:
    PYTHONPATH=$PWD python scripts/create_db.py


migrate-new migration_description:
    uv run alembic revision -m {migration_description}


migrate-new-autogenerate migration_description:
    uv run alembic revision -m {migration_description} --autogenerate


migrate-up:
    PYTHONPATH=$PWD uv run alembic upgrade head
